### PR TITLE
add missing scripts folder

### PR DESCRIPTION
**Pull request by sinisaos**
Adding missing scripts folder

### CODE REVIEW

**Comment by SWimplifyDev** [comment]
Thanks @sinisaos , I am having some issues while trying to run the app with the new asgi_csrf package, not sure why? I commented few lines and it worked
Screenshot 2024-08-01 at 4 01 14 PM

**Comment by sinisaos** [comment]
@SWimplifyDev I don't know, everything works for me with the shell scripts added in the latest PR (`*.sh` was in `.gitignore` and that was the reason why the scripts folder was not in the main branch). Did you provide the `.env` file in the root directory because `asgi_csfr` use `settings.secret_key` from `.env`?

You also need to add `csrftoken` to any `POST` form you have

https://github.com/SWimplifyDev/FastAuthBase/blob/3c0265c182a326961b4a728bcf88b914cea70221/templates/components/logout-modal.html#L13-L15

This should be like this

```html
<form method="post" action="/logout">
    <input type="hidden" name="csrftoken" value="{{ request.scope.csrftoken() }}">
    <button type="submit" class="btn btn-custom">Yes</button>
</form>
```

I see that you moved all hidden field with `csrftoken` from your forms in latest commit. Without it, `asgi_csrf` will not work.

**Comment by SWimplifyDev** [comment]
I just removed temporally because while I was finding the issue I noticed that I can not have app declare twice:
`app = FastAPI()

app = asgi_csrf(app,
                signing_secret=settings.secret_key,
                always_set_cookie=True)`

How does it run on you side, its intriguing.

**Comment by sinisaos** [comment]
@SWimplifyDev I have an `.env.example` with a `secret_key` in the root directory. Then I run `./scripts/env.sh` to create the `.env` file with the `secret_key`. Then I start the server with `./scripts/start.sh` and everything works. Maybe you can try changing FastAPI app to `fastapi_app` or something, like this.

```python
fastapi_app = FastAPI()

# you also must change to fastapi_app in all endpoints

 app = asgi_csrf(fastapi_app,
     signing_secret=settings.secret_key,
     always_set_cookie=True,
)
```
 It might be a problem with your `start-python.sh`. I don't know. Everything is working as expected from my end, with my version of code. I can't try your changes until tomorrow.

**Comment by sinisaos** [comment]
@SWimplifyDev I tried your changes and I think the problem is `fastapi-cli` (never used that new FastAPI thing) because it doesn't treat `asgi_csrf` (which is an asgi app/middleware) as a FastAPI/ASGI app. If you directly start the server with `uvicorn main:app` (and add `csrftoken` as a hidden field in all POST forms), everything is fine and csrftoken is generated (you can inspect the browser console to see that this is true). If you want to use `fastapi-cli`, maybe you can try [this library](https://github.com/aekasitt/fastapi-csrf-protect) and hope for a better result, but the implementation is up to you (if you want to go that way, feel free to close my latest PR). Second question. Why don't you use Starlette directly because you use server-side templates? FastAPI is useful for web apis (openapi documentation out of the box) but I think Starlette is a better choice for a traditional web application with server-side templates.

**Comment by SWimplifyDev** [comment]
@sinisaos, that makes sense. I noticed that the last release of asgi_csrf was in 2021. I'm currently checking out the library you mentioned, and it seems to function similarly to the one you implemented. I'll give it a try and see how it goes.

Regarding your second question, as developers, we're always on the lookout for the right tools, frameworks, and languages to make our work easier and more productive. I'm experimenting with FastAPI because it has garnered significant attention and support from the developer community. It's versatile, allowing for the creation of both APIs and web applications.

Starting this project is my attempt to bring back the simplicity of web development from the past, before the complexities of modern front-end and back-end separation. I've noticed a trend among companies to reduce complexity and dependencies in front-end development. By leveraging the power of server-side applications and the simplicity of HTMX, we can achieve what JavaScript engineers accomplish with thousands of lines of code executed in the client's browser. Check out this interesting video: [Youtube](https://www.youtube.com/watch?v=wIzwyyHolRs).

**Comment by sinisaos** [comment]
@SWimplifyDev I tried the `fastapi-csrf-protect` and it works with `fastapi-cli`. It's a lot more work to set up and get ready to use than `asgi_csrf`, but it's work. I'm going to close this PR because you don't use shell scripts in that way.

**Pull request closed without merging**
